package FeatureModel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_VariantTime extends EnumerationDescriptorBase {

  public EnumerationDescriptor_VariantTime() {
    super(0x50a851c9401b45e3L, 0x83bb77ced6965729L, 0x5fd48bfb9a3fb7fcL, "VariantTime", "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732284");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember__alpha__0 = new EnumerationDescriptor.MemberDescriptor("_alpha_", "_alpha_", 0x5fd48bfb9a3fb7fdL, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732285");
  private final EnumerationDescriptor.MemberDescriptor myMember_analysis_0 = new EnumerationDescriptor.MemberDescriptor("analysis", "analysis", 0x5fd48bfb9a3fb7feL, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732286");
  private final EnumerationDescriptor.MemberDescriptor myMember_design_0 = new EnumerationDescriptor.MemberDescriptor("design", "design", 0x5fd48bfb9a3fb801L, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732289");
  private final EnumerationDescriptor.MemberDescriptor myMember_compile_0 = new EnumerationDescriptor.MemberDescriptor("compile", "compile", 0x5fd48bfb9a3fb805L, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732293");
  private final EnumerationDescriptor.MemberDescriptor myMember_link_0 = new EnumerationDescriptor.MemberDescriptor("link", "link", 0x5fd48bfb9a3fb80aL, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732298");
  private final EnumerationDescriptor.MemberDescriptor myMember_assembly_0 = new EnumerationDescriptor.MemberDescriptor("assembly", "assembly", 0x5fd48bfb9a3fb810L, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732304");
  private final EnumerationDescriptor.MemberDescriptor myMember_install_0 = new EnumerationDescriptor.MemberDescriptor("install", "install", 0x5fd48bfb9a3fb817L, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732311");
  private final EnumerationDescriptor.MemberDescriptor myMember_runtime_launch_0 = new EnumerationDescriptor.MemberDescriptor("runtime_launch", "runtime.launch", 0x5fd48bfb9a3fb81fL, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732319");
  private final EnumerationDescriptor.MemberDescriptor myMember_runtime_init_0 = new EnumerationDescriptor.MemberDescriptor("runtime_init", "runtime.init", 0x5fd48bfb9a3fb828L, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732328");
  private final EnumerationDescriptor.MemberDescriptor myMember_runtime_run_0 = new EnumerationDescriptor.MemberDescriptor("runtime_run", "runtime.run", 0x5fd48bfb9a3fb832L, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732338");
  private final EnumerationDescriptor.MemberDescriptor myMember__omega__0 = new EnumerationDescriptor.MemberDescriptor("_omega_", "_omega_", 0x5fd48bfb9a3fb83dL, "r:e3c38147-e3aa-4a42-a8a5-17ba87d04ca1(FeatureModel.structure)/6905298041406732349");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x50a851c9401b45e3L, 0x83bb77ced6965729L, 0x5fd48bfb9a3fb7fcL, 0x5fd48bfb9a3fb7fdL, 0x5fd48bfb9a3fb7feL, 0x5fd48bfb9a3fb801L, 0x5fd48bfb9a3fb805L, 0x5fd48bfb9a3fb80aL, 0x5fd48bfb9a3fb810L, 0x5fd48bfb9a3fb817L, 0x5fd48bfb9a3fb81fL, 0x5fd48bfb9a3fb828L, 0x5fd48bfb9a3fb832L, 0x5fd48bfb9a3fb83dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember__alpha__0, myMember_analysis_0, myMember_design_0, myMember_compile_0, myMember_link_0, myMember_assembly_0, myMember_install_0, myMember_runtime_launch_0, myMember_runtime_init_0, myMember_runtime_run_0, myMember__omega__0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "_alpha_":
        return myMember__alpha__0;
      case "analysis":
        return myMember_analysis_0;
      case "design":
        return myMember_design_0;
      case "compile":
        return myMember_compile_0;
      case "link":
        return myMember_link_0;
      case "assembly":
        return myMember_assembly_0;
      case "install":
        return myMember_install_0;
      case "runtime_launch":
        return myMember_runtime_launch_0;
      case "runtime_init":
        return myMember_runtime_init_0;
      case "runtime_run":
        return myMember_runtime_run_0;
      case "_omega_":
        return myMember__omega__0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
