package TacticType.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new AssetType_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Literal_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Parameter_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Procedure_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new RegexConstraint_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new TacticType_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new Parameter_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x1d13a7c5fe75b1fcL), MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x1d13a7c5fe75b402L), MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x5fd48bfb9a42636bL), MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x5fd48bfb9a42636aL), MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x1d13a7c5fe75feb8L), MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x5fd48bfb9a4262ebL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x5fd48bfb9a42636bL)).seal();
}
