package TacticType.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_variantTime extends EnumerationDescriptorBase {

  public EnumerationDescriptor_variantTime() {
    super(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x5fd48bfb9a4262faL, "variantTime", "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907130");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember__alpha__0 = new EnumerationDescriptor.MemberDescriptor("_alpha_", "_alpha_", 0x5fd48bfb9a4262fbL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907131");
  private final EnumerationDescriptor.MemberDescriptor myMember_analysis_0 = new EnumerationDescriptor.MemberDescriptor("analysis", "analysis", 0x5fd48bfb9a4262fcL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907132");
  private final EnumerationDescriptor.MemberDescriptor myMember_design_0 = new EnumerationDescriptor.MemberDescriptor("design", "design", 0x5fd48bfb9a4262ffL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907135");
  private final EnumerationDescriptor.MemberDescriptor myMember_compile_0 = new EnumerationDescriptor.MemberDescriptor("compile", "compile", 0x5fd48bfb9a426303L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907139");
  private final EnumerationDescriptor.MemberDescriptor myMember_link_0 = new EnumerationDescriptor.MemberDescriptor("link", "link", 0x5fd48bfb9a426308L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907144");
  private final EnumerationDescriptor.MemberDescriptor myMember_assembly_0 = new EnumerationDescriptor.MemberDescriptor("assembly", "assembly", 0x5fd48bfb9a42630eL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907150");
  private final EnumerationDescriptor.MemberDescriptor myMember_install_0 = new EnumerationDescriptor.MemberDescriptor("install", "install", 0x5fd48bfb9a426315L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907157");
  private final EnumerationDescriptor.MemberDescriptor myMember_runtime_launch_0 = new EnumerationDescriptor.MemberDescriptor("runtime_launch", "runtime.launch", 0x5fd48bfb9a42631dL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907165");
  private final EnumerationDescriptor.MemberDescriptor myMember_runtime_init_0 = new EnumerationDescriptor.MemberDescriptor("runtime_init", "runtime.init", 0x5fd48bfb9a426326L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907174");
  private final EnumerationDescriptor.MemberDescriptor myMember_runtime_run_0 = new EnumerationDescriptor.MemberDescriptor("runtime_run", "runtime.run", 0x5fd48bfb9a426330L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907184");
  private final EnumerationDescriptor.MemberDescriptor myMember__omega__0 = new EnumerationDescriptor.MemberDescriptor("_omega_", "_omega_", 0x5fd48bfb9a42633bL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/6905298041406907195");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x5fd48bfb9a4262faL, 0x5fd48bfb9a4262fbL, 0x5fd48bfb9a4262fcL, 0x5fd48bfb9a4262ffL, 0x5fd48bfb9a426303L, 0x5fd48bfb9a426308L, 0x5fd48bfb9a42630eL, 0x5fd48bfb9a426315L, 0x5fd48bfb9a42631dL, 0x5fd48bfb9a426326L, 0x5fd48bfb9a426330L, 0x5fd48bfb9a42633bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember__alpha__0, myMember_analysis_0, myMember_design_0, myMember_compile_0, myMember_link_0, myMember_assembly_0, myMember_install_0, myMember_runtime_launch_0, myMember_runtime_init_0, myMember_runtime_run_0, myMember__omega__0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "_alpha_":
        return myMember__alpha__0;
      case "analysis":
        return myMember_analysis_0;
      case "design":
        return myMember_design_0;
      case "compile":
        return myMember_compile_0;
      case "link":
        return myMember_link_0;
      case "assembly":
        return myMember_assembly_0;
      case "install":
        return myMember_install_0;
      case "runtime_launch":
        return myMember_runtime_launch_0;
      case "runtime_init":
        return myMember_runtime_init_0;
      case "runtime_run":
        return myMember_runtime_run_0;
      case "_omega_":
        return myMember__omega__0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
