package TacticType.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_typeAT extends EnumerationDescriptorBase {

  public EnumerationDescriptor_typeAT() {
    super(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x1d13a7c5fe75b1ffL, "typeAT", "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934655");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_integer_0 = new EnumerationDescriptor.MemberDescriptor("integer", "integer", 0x1d13a7c5fe75b200L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934656");
  private final EnumerationDescriptor.MemberDescriptor myMember_string_0 = new EnumerationDescriptor.MemberDescriptor("string", "string", 0x1d13a7c5fe75b201L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934657");
  private final EnumerationDescriptor.MemberDescriptor myMember_boolean_0 = new EnumerationDescriptor.MemberDescriptor("boolean", "boolean", 0x1d13a7c5fe75b204L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934660");
  private final EnumerationDescriptor.MemberDescriptor myMember_float_0 = new EnumerationDescriptor.MemberDescriptor("float", "float", 0x1d13a7c5fe75b208L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934664");
  private final EnumerationDescriptor.MemberDescriptor myMember_directory_0 = new EnumerationDescriptor.MemberDescriptor("directory", "directory", 0x1d13a7c5fe75b20dL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934669");
  private final EnumerationDescriptor.MemberDescriptor myMember_filename_0 = new EnumerationDescriptor.MemberDescriptor("filename", "filename", 0x1d13a7c5fe75b213L, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934675");
  private final EnumerationDescriptor.MemberDescriptor myMember_URI_0 = new EnumerationDescriptor.MemberDescriptor("URI", "URI", 0x1d13a7c5fe75b21aL, "r:cd52f2f0-5fba-4923-9ee5-8cb501b92b60(TacticType.structure)/2095202720476934682");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xd7f4c9b7457c4ddfL, 0x8db169fc1d011181L, 0x1d13a7c5fe75b1ffL, 0x1d13a7c5fe75b200L, 0x1d13a7c5fe75b201L, 0x1d13a7c5fe75b204L, 0x1d13a7c5fe75b208L, 0x1d13a7c5fe75b20dL, 0x1d13a7c5fe75b213L, 0x1d13a7c5fe75b21aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_integer_0, myMember_string_0, myMember_boolean_0, myMember_float_0, myMember_directory_0, myMember_filename_0, myMember_URI_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "integer":
        return myMember_integer_0;
      case "string":
        return myMember_string_0;
      case "boolean":
        return myMember_boolean_0;
      case "float":
        return myMember_float_0;
      case "directory":
        return myMember_directory_0;
      case "filename":
        return myMember_filename_0;
      case "URI":
        return myMember_URI_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
